spring:
  application:
    name: sbapi
  datasource:
    url: jdbc:postgresql://localhost:5432/hr_trainings
    username: appuser
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        #https://docs.jboss.org/hibernate/orm/5.4/userguide/html_single/Hibernate_User_Guide.html#configurations-hbmddl
        ddl-auto: update # (create | create-drop | update | validate | none)
        jdbc:
          time_zone: UTC

  logging:
    level:
    # villanidev.demo: DEBUG
      org.hibernate.SQL: DEBUG
    # hibernate show query param values
      org.hibernate.type.descriptor.sql: TRACE
  management:
    endpoints:
      web:
        exposure:
          include: "*"
          exclude: "env,beans"
